### ISSUE TITLE
Quick Launch Timer

### ISSUE THREAD

**Issue by PiwwowPants** [JumpMaster/QuickAuth#17]
When upgrading from 1.x to 2.x with by compiling from this code, my codes are wiped from the watch but not the phone. This causes the countdown timer to no longer work when launched from Quick Launch as well as uses up extra slots, since there are broken keys inside.

[INFO    ] D main.c:1037 INFO: NO CODES ON WATCH!
[INFO    ] D main.c:859 INFO: Key count from watch: 0
[INFO    ] D main.c:860 INFO: Key count from phone: 4

**Comment by JumpMaster** [comment]
Issue resolved with release 2.1
