### ISSUE TITLE
feature request: re-order tokens

### ISSUE THREAD

**Issue by ianonavy** [JumpMaster/QuickAuth#18]
It'd be great if you could re-order the tokens on the watch by say long pressing middle button while selecting an app. Being able to re-order them on my phone via the settings would also work.

**Comment by JumpMaster** [comment]
I agree especially with the update I'm working on that has two different layouts. It's on my todo list and I'm pleased it's now on my GitHub to do list too :)

**Comment by JumpMaster** [comment]
This is now implemented in version 2.4.

Press the select key to open the select menu, long press the select key and use the up/down keys to change it's position. Tap the select key again to set its new position.
