### ISSUE TITLE
Can not add secret > 64 characters

### ISSUE THREAD

**Issue by fidian** [JumpMaster/QuickAuth#19]
I am generating a key for use with GitLab.  It's using a 128-byte secret.  When I compare the numbers versus Google Authenticator, the numbers are different.  I traced this down to two problems:

1.  The JavaScript does not alert me that a key is too long.
2.  My secret key for GitLab is unable to be stored in the phone because it has a max length of 64 characters.

**Comment by JumpMaster** [comment]
Fixed in version 2.3
