### ISSUE TITLE
Feature Request: Edit Spaces

### ISSUE THREAD

**Issue by thequicksilver** [JumpMaster/QuickAuth#20]
Unless I'm missing something, I see no way to edit the authenticators I've put into the device. Not like the auth key, obviously, but the name, colors, etc. I can see after entering one that I have "15 Spaces Left," and I can see that I can delete the authenticator from the watch itself, but nothing seems to imply that I can edit it in any way after the fact.

**Comment by JumpMaster** [comment]
If you enter the same auth key with a new label the label will be updated.

Colors and fonts are not tied to auth keys. They are set no matter which key is being viewed. They can be changed without having to enter a key on the configuration page.

**Comment by thequicksilver** [comment]
I see. The layout of the settings page made it seem like you could use a different color pair per-auth key.
