### ISSUE TITLE
QR code reading

### ISSUE THREAD

**Issue by chasepeeler** [JumpMaster/QuickAuth#21]
Love this app. Actually regenerated all of the keys for the phone app so that I could add the key in both my phone and watch! Most annoying part though is typing in the key! I know there are HTML5 libraries out there for dealing with QR codes - have you played around with any of them? I'd be willing to fork this and see what I could do, but I wanted to make sure it wasn't something you've messed around with already and determined wasn't feasible.

**Comment by JumpMaster** [comment]
I already have it built and ready to go. Two issues. Camera access from Safari on iOS isn't possible so it won't work on iPhones. Secondly the Pebble app doesn't have Camera permissions and the webui isn't configured to handle camera requests. I put an email into Pebble support mid-July but I haven't had a reply. I'll leave those open to track it.

**Comment by chasepeeler** [comment]
Darn. I'm on iOS too, so even if you get the second issue resolved, there isn't much I could do to help. 

Anyway, love the app, like I said - only other thing that would be better is if the authenticator app actually synced with the watch app - but since that would require rewriting the authenticator app to offer companion functionality, I don't see that happening :-)
