### ISSUE TITLE
Chalk / Round + Token Backup

### ISSUE THREAD

**Issue by n4ru** [JumpMaster/QuickAuth#23]
Just bought the new Pebble and was disappointed to see support was not added. At the very least, is it possible to back up our tokens from the watch? This was my most important app and without it I'm gonna have to regenerate quite a few 2FA codes and reenter them across all 4 of my Pebbles. :/

**Comment by JumpMaster** [comment]
Hi @n4ru 

Would you be able to test a new version of the app on your PTR? I don't overly trust the emulator before release.

Thanks,
Kev

**Comment by n4ru** [comment]
Sure, post it here.

**Comment by JumpMaster** [comment]
Thanks!

https://dl.dropboxusercontent.com/u/18412241/QuickAuth-ptr.pbw

Could you test adding multiple codes, sorting codes (long press select while in the code select screen), and both display types (long press select on the front screen). If everything looks good I just have to test it in my OG Pebbel with firmware 2 and 3.

**Comment by n4ru** [comment]
Currently on vacation but brought my Round with me. Posting here to remind myself to test this out later today.

**Comment by JumpMaster** [comment]
QuickAuth 3.0 released with Round/Chalk support.
