### ISSUE TITLE
Provide HTTPS support or use data base64 page for confiruation

### ISSUE THREAD

**Issue by TheSkorm** [JumpMaster/QuickAuth#25]
Using an external site for the config page is insecure. Should either use a data URI to host the page locally or at least use HTTPS to host the page.

**Comment by JumpMaster** [comment]
It is completely secure.  No data is transferred to the website as there is only a JavaScript post back to the Pebble app on your device.

**Comment by TheSkorm** [comment]
This isn't completely secure. You can use a MITM proxy to inject javascript into the page to report the key  back to another server.

**Comment by JumpMaster** [comment]
Yes that;s true there is a theoretical MITM attack when not using HTTPS. The current server cannot use HTTPS as there's only a single IP and it's already hosting a SSL website with a different host header. I will look into hosting it directly on GitHub to use HTTPS although you could argue that would be even less secure.

**Comment by TheSkorm** [comment]
There is an option of using base64 encoded uri to load the page without using a server

**Comment by JumpMaster** [comment]
Where would the webpage, javascript, and assets be hosted?  Do you have a list to used the base64 uri instead of a server?

**Comment by TheSkorm** [comment]
You can have the assets also in base64 in the page.

Here is an example https://gist.github.com/tomgidden/87aeee7209f5bed813bf and Mozilla reference https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs

**Comment by JumpMaster** [comment]
Looks possible but it wont be easy with the current html layout.

https://github.com/JumpMaster/QuickAuth/tree/master/html/v20

I'll accept a pull request if your able to do it.

Thanks

**Comment by TheSkorm** [comment]
I did test this by manually base64 encoding everything. Took about 15 minutes to do. Do you have a build script you use and the sources for the jquery mobile resources. The live HTML seems to point to different sources than the got project.

**Comment by JumpMaster** [comment]
I've added previous versions of the configuration page including the current version v25 (for app version 2.5)

I don't use any build scripts for the HTML. I edit it using Notepad++ to keep it as clean as possible.
