### ISSUE TITLE
Any plans to support the Round model?

### ISSUE THREAD

**Issue by AdeTheux** [JumpMaster/QuickAuth#28]
I've switched to a Pebble Time Round and realised the App is now being displayed as "not supported". I miss QuickAuth a lot already :)

**Comment by JumpMaster** [comment]
Yes but I haven't been able to get anyone to test it...

https://dl.dropboxusercontent.com/u/18412241/QuickAuth-ptr.pbw

**Comment by AdeTheux** [comment]
Ah, brilliant, thanks! Just installed it, I'll keep you posted here if I face any issues. 
Love this App!

**Comment by AdeTheux** [comment]
Working fine so far.
Is there a way to edit the key names? I've got one which is too long to be displayed correctly.

**Comment by JumpMaster** [comment]
If you enter the same key with a different name it will update the existing entry.

**Comment by JumpMaster** [comment]
QuickAuth 3.0 released with Round/Chalk support.
