### ISSUE TITLE
Add Teamviewer 2FA support

### ISSUE THREAD

**Issue by e-alfred** [JumpMaster/QuickAuth#29]
Hello,

it would be great if this app would support Teamviewer 2FA as well. It is a 16 digit code, but if I enter it, the login won't work mentioning that this is an invalid code.

**Comment by JumpMaster** [comment]
I've looked at the Teamviewer 2FA how to and it show it using the Google Authenticator app.  If it works with Google Authenticator then it will work with QuickAuth.

**Comment by e-alfred** [comment]
Hello,

yes, it works fine with Google Authenticator, but if I enter the 16 digit code for the recovery I only get invalid values. Do I have to decode the QR code and apply it instead of the recovery code?

**Comment by JumpMaster** [comment]
I would read the QR code using a barcode scanner and get the code from there. It seems that Teamviewer are not giving you the code used by Google Authenticator.

**Comment by e-alfred** [comment]
The code in digit form is now available next to the QR image. It works now, awesome! The recovery code is different, though.
