### ISSUE TITLE
Request: Support more than 16 keys

### ISSUE THREAD

**Issue by nhinds** [JumpMaster/QuickAuth#30]
I enable multi-factor authentication on every site I use that supports it, and I've currently got 18 keys in my TOTP app on my phone. I'd love to be able to add the missing ones to QuickAuth.

Any particular reason for the 16 key limit at the moment?

**Comment by JumpMaster** [comment]
No I don't believe there is. A limit has to be set somewhere and 16 seemed a good choice. I'll up the limit to 24 in the next release as long as I don't run into any limits on the watch or javascript portion of the app.

**Comment by nhinds** [comment]
Thanks :)

**Comment by JumpMaster** [comment]
QuickAuth 3.0 released with 30 spaces for keys.
