### ISSUE TITLE
Use https with configuration screen

### ISSUE THREAD

**Issue by Lesterpig** [JumpMaster/QuickAuth#31]
Hi,

Thank you for this amazing app! It's working perfectly.
However, I've some concerns regarding the fact that the configuration screen is not authenticated by TLS.

See https://github.com/JumpMaster/QuickAuth/blob/master/src/js/pebble-js-app.js#L238

According to the code, the secret key is not transmitted to the configuration webserver, but someone could spoof the identity of the website, leaking the secret keys by changing the code.

Adding a TLS certificate would certainly lower the probability of a spoof in this case. But maybe Pebble doesn't allow https configuration?

Thanks

**Comment by bcaller** [comment]
Actually, it should now be possible to embed the configuration page in the app and remove the need for an external server: https://developer.pebble.com/blog/2016/06/24/introducing-clay/

**Comment by bcaller** [comment]
I made a start.
https://github.com/JumpMaster/QuickAuth/compare/master...bcaller:offline-config

**Comment by JumpMaster** [comment]
That's awesome! Thanks. I'll be switching to clay.  I really screwed up adding Pebble Chalk support and need to revert the last few changes.  Then I can add Pebble Time 2 support.

**Comment by bcaller** [comment]
Great to hear you're working on it. I'll leave it to you then.

**Comment by JumpMaster** [comment]
QuickAuth 3.0 released with local configuration screen.
