### ISSUE TITLE
Feature request: Key management screen in the Pebble App

### ISSUE THREAD

**Issue by WoLpH** [JumpMaster/QuickAuth#32]
It seems that when I open the QuickAuth settings I am only able to add new keys. Is there any way to remove, edit and replace existing keys?

One of my keys has a typo in the name which I would like to change. And one of them is simply invalid and needs to be replaced. I see the clear all option but that's a bit drastic.

**Comment by nhinds** [comment]
To remove entries, with QuickAuth open on your watch press <select> to open the menu, <up>/<down> to find the entry you want to delete, <select> again to open the "default or delete?" option, then the button beside the trash can icon will delete the entry from your watch.

To replace entries, remove them and add a new one.

To rename entries, enter the same secret into the configuration page on your phone with a new name. The existing entry will be updated with the new name.

**Comment by WoLpH** [comment]
Ah, brilliant. Thank you :)

Although I would opt for the feature of having an editable list from the phone interface.

**Comment by JumpMaster** [comment]
It's not going to be possible. Especially with the switch to Pebble Clay.
