### ISSUE TITLE
Support for 8-digits OTP (e.g., Blizzard Battle.net Authenticator - OTP)

### ISSUE THREAD

**Issue by Mnkai** [JumpMaster/QuickAuth#33]
Some OTPs tend to use 8 digits instead of current 6 digits. (For example, Blizzard Battle.net OTP)

They are both TOTP authenticators, only digit window is different. I think QuickAuth can be modified to support Blizzard OTP by tweaking small parameters and few lines.

Python implementation of Blizzard OTP can be found here - (https://github.com/jleclanche/python-bna)
(deprecated) Pebble codes can be found here - (https://github.com/Perlmint/pebbleOTP)
FreeOTP supports Blizzard OTP currently. (https://fedorahosted.org/freeotp/)
WinAuth has implementation of Blizzard OTPs (C#) here. You can look at Blizzard OTP's parameter. (https://github.com/winauth/winauth/blob/92faf643660c63e4d4a2f7ad664d7947c6936f02/Authenticator/BattleNetAuthenticator.cs)

**Comment by Mnkai** [comment]
If full support (Making authenticator with random digits + region w/ actual OTP code generating) is difficult within pebble due to space etc., users can always use python-bna to make authenticator serial and register with Blizzard user console, and copy secret code of OTP algorithm only from it's configuration file (~/.config/bna/bna.conf) to QuickAuth.

(Be aware than python-bna's secret code is encoded with hex, it can be decoded via this method by Perlmint)
  ```python
import base64, binascii
print base64.b32encode(binascii.unhexlify('YOUR_BATTLE_NET_SECRET'))
```

**Comment by JackZielke** [comment]
I was coming here to ask for the same thing.  If you put the secret in, you only see the last 6 digits and can not log in.
