### ISSUE TITLE
Use the "Google Prompt" with QuickAuth?

### ISSUE THREAD

**Issue by joejacker** [JumpMaster/QuickAuth#35]
Hi there, would it be possible in any way to implement the new(ish) feature in Google 2SV, where you (on your phone) just tap the OK prompt, when logging in? This bypasses the code entry and is much easier. It would be amazing to have this on the Pebble as well, just having to push one of the buttons when requested.

I'm not a coder, and have no idea if this is even doable. What do you think dev? Cheers!

**Comment by JumpMaster** [comment]
It doesn't seem to be possible.  I wish it was!
