### ISSUE TITLE
DST issues with QuickAuth

### ISSUE THREAD

**Issue by Skyssx** [JumpMaster/QuickAuth#36]
Not sure if this is handled when connected to a phone, but I smashed my phone 29OCT, and haven't had a connection to it since then. The Pebble2 itself handled DST on its own, however I discovered today that QuickAuth did not. I was unable to log in using my 2FA keys until I set my time zone to a GMT-4 (Caracas), and it started working fine.

**Comment by JumpMaster** [comment]
In the current implementation timezone information is received from the phone.
