### ISSUE TITLE
Please provide option not to store secrets on phone.

### ISSUE THREAD

**Issue by vsrinu26f** [JumpMaster/QuickAuth#39]
I would rather enter secrets again on firmware update than store them on phone.

I like secrets not leave pebble.

**Comment by JumpMaster** [comment]
Would putting a password on your phone not be a better option?

The pebble is far less secure as there is no option to password protect it and it's easy to install a custom app with the same uuid that writes the codes to log.

Of you're that concerned you should not be using third party Google authenticator apps.

**Comment by vsrinu26f** [comment]
Most of the time its malware on phone i am worried. 

Idea is to make it difficult. You dont need to password protect. All i need is checkbox use phone storage for backup and recovery. 

Thank you
Srinivas

**Comment by JumpMaster** [comment]
The question is does Pebble store user data on the phone in an unencrypted format?

**Comment by louwers** [comment]
On the iPhone at least, app data is encrypted if I am not mistaken (as long as you set a password).

> The pebble is far less secure as there is no option to password protect it and it's easy to install a custom app with the same uuid that writes the codes to log.

Why not store the keys encrypted on the Pebble, and prompt the user for a password when they want to use the app? The problem will be obtaining 80 some bits of password data on a device that has only four buttons... Hmm... Maybe accelerator data? 😆
