### ISSUE TITLE
All codes disappeared?

### ISSUE THREAD

**Issue by ebr** [JumpMaster/QuickAuth#40]
Perhaps this happened after an update - I do not know. Just noticed this right now.
Pebble Time Steel, v4.3.
Opening the app on the watch just shows a black screen. That was surprising, so I went into the app settings on my phone, only to find that all of the codes are gone and i have "25 slots remaining".
I assume there's no way to get those codes back without generating new ones. 
(i do make sure to set up both my phone and the watch when generating a new code, so not all is lost - i can still use my phone for 2FA.)

**Comment by ebr** [comment]
soooo that's a `wontfix` then?

**Comment by JumpMaster** [comment]
Sorry I assumed you would have fixed this by then. A black screen means the foreground and background colors are the same. Change them in the settings menu.

**Comment by ebr** [comment]
No, all the codes are actually gone. I haven't fixed it as it would require me to set up 2FA from scratch for all the services I use, and without knowing they'll stick around, I'm not sure I can justify the effort. have just been using my phone since then.
Just to confirm - since the codes have disappeared from the watch, there's no way to re-send them to the watch from the app? (I assume the answer is "no").
